### ISSUE TITLE
The "redirect URI" parameter is not correct

### ISSUE THREAD

**Issue by codingbutstillalive** [teramonagi/fitbitr#17]
Hello!

Great work, thanks for that. However, I am having a problem:

When I run the command oauth_token() it asks me to follow a link in my webbrowser. This is supposed to be the request for the authorization code and the prompt tells me I should copy and paste it. That's all nice and fine, but the fitbit authorization page in my browser instead gives the error message:

`"Developer information: invalid_request - Invalid redirect_uri parameter value"`

I have no option to configure this parameter. So, this is **error No1**.

Second, if I insert a valid redirect URI manually (including the HTML escape characters), it successfully shows me the correct Fitbit App authorization page, but after pressing "Allow", there is yet another error message in the R command line: 

```
"Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token."
```

This is **error No2**.

When did you check the code for the last time? Seems to be broken on multiple locations :(

Best regards

**Comment by teramonagi** [comment]
I'll fix it !

**Comment by codingbutstillalive** [comment]
Thanks for you support!

**Comment by teramonagi** [comment]
Fixed it on the following PR: https://github.com/teramonagi/fitbitr/pull/19 .

This is caused by the change of fitbit API which does not allow http://localhost:1410/ as a callback URL.

**Comment by codingbutstillalive** [comment]
Thanks! I will give it a try these days. Great support!

**Comment by codingbutstillalive** [comment]
I could only check this today, and it still gives the same error message!

> Developer information: invalid_request - Invalid redirect_uri parameter value
