### ISSUE TITLE
Error upon invoking "oauth_token()"

### ISSUE THREAD

**Issue by codingbutstillalive** [teramonagi/fitbitr#21]
I got the following error message:

>Error in as.environment(pos) :no entry "package:httr" in search path

I checked that the package is installed, and also re-installed manually.

Best regards,
Sebastian

**Comment by codingbutstillalive** [comment]
Okay, that one is done. One has to load the httr-package manually.

**Comment by teramonagi** [comment]
It should be loaded automatically in this package.
I'll do it.

**Comment by teramonagi** [comment]
This issue is also fixed by the PR https://github.com/teramonagi/fitbitr/pull/23

**Comment by teramonagi** [comment]
@codingbutstillalive 
It might be fixed in the PR https://github.com/teramonagi/fitbitr/pull/23 
Could I ask you to try again please?
