### ISSUE TITLE
"Invalid_request - Invalid redirect_uri parameter value"

### ISSUE THREAD

**Issue by codingbutstillalive** [teramonagi/fitbitr#22]
Hello!

The issue that was already discussed and closed here:

https://github.com/teramonagi/fitbitr/issues/17

... is not solved. I still get the above error message!

Here is the setting of my app at https://dev.fitbit.com:

- OAuth 2.0 Application Type: Personal
- Callback URL: http://localhost:1410/
- Default Access Type: Read & Write

I really need to get this whole thing working. Could you please help me @teramonagi.

Best regards,
Sebastian

**Comment by codingbutstillalive** [comment]
Is this again a problem of a API change of Fitbit?

**Comment by codingbutstillalive** [comment]
Hi!

Is this project still alive? I wonder.

**Comment by teramonagi** [comment]
Yes! I'm alive!

**Comment by teramonagi** [comment]
Hmm, it looks like that fitbir changed their interface again.

**Comment by teramonagi** [comment]
@codingbutstillalive
It might be fixed in the PR #23
Could I ask you to try again please?

**Comment by darkniobe** [comment]
I had this same problem. Fitbit's OAuth mechanism is very finicky about the trailing "/" in the callback URI.
I was able to fix the problem by making sure the trailing "/" is present in the app configuration on Fitbit's website.
I don't know if it matters but I used "http://localhost:1410/" in all of the following fields:
Application Website *
Organization Website *
Callback URL *

After making that change the call to oauth_token() worked as expected.

**Comment by teramonagi** [comment]
I completely agree with your comment "Fitbit's OAuth mechanism is very finicky about the trailing "/" in the callback URI.".

@codingbutstillalive
Current master branch's code should work.
You can use this package if you have a time :)

**Comment by codingbutstillalive** [comment]
Hi there!

Thanks for the updates. I finally switched to using httr directly and got the whole thing running after going through the same problems with the trailing "/".

http://stackoverflow.com/questions/41120254/accessing-fitbit-intra-day-time-series-with-httr-invalid-redirect-uri

I deleted my codes based on fitbitr. Sorry.

**Comment by elessarrr** [comment]
> I had this same problem. Fitbit's OAuth mechanism is very finicky about the trailing "/" in the callback URI. I was able to fix the problem by making sure the trailing "/" is present in the app configuration on Fitbit's website. I don't know if it matters but I used "http://localhost:1410/" in all of the following fields: Application Website * Organization Website * Callback URL *
> 
> After making that change the call to oauth_token() worked as expected.

@darkniobe bro i love you cos this issue took up half my day and i was considering moving to management cos programming was now beyond me but this stupid backslash was all i needed
