### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by squirrelB** [teramonagi/fitbitr#24]
Hi, I've tried using both teramonagi/fitbitr and Avsecz/fitbitr, and both times I'm getting an error message:
"The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.
Developer information: invalid_request - Invalid redirect_uri parameter value"
Not sure why. Callback URL is http://localhost:1410, "read-only" access type. Have tried going to the www.fitbit/oauth2/authorize... and allowed and got message "Authentication complete. Please close this page and return to R." Can't figure out what I'm doing wrong and how to fix.

**Comment by af12066** [comment]
I also encountered the same error.

In [httr](https://github.com/r-lib/httr) package, the default redirect uri is set to `"urn:ietf:wg:oauth:2.0:oob"` (see https://github.com/r-lib/httr/blob/master/R/oauth-init.R#L85) and this URI is also applied to the fitbitr package.
However Fitbit API's redirect URL must be the same as callback URL you set up in https://dev.fitbit.com/apps (see screenshot below. `urn:ietf:wg:oauth:2.0:oob` can't be used).  
<img width="399" alt="fitbit" src="https://user-images.githubusercontent.com/10768439/30480368-5b6e5162-9a54-11e7-8e90-f10ffc0c71ae.png">

So I think that [token.R#L25-31](https://github.com/teramonagi/fitbitr/blob/master/R/token.R#L25-L31) should be changed as follows:
```R
  request <- "https://api.fitbit.com/oauth2/token"
  authorize <- "https://www.fitbit.com/oauth2/authorize"
  access <- "https://api.fitbit.com/oauth2/token"
  redirect <- "http://localhost:8080" # FIXME: Should not be hard-coded
  endpoint <- httr::oauth_endpoint(request, authorize, access)
  myapp <- httr::oauth_app("r-package", key, secret, redirect_uri=redirect)
  scope <- c("sleep", "activity", "heartrate", "location", "nutrition", "profile", "settings", "social", "weight")
  httr::oauth2.0_token(endpoint, myapp, scope=scope, use_basic_auth=TRUE, cache=FALSE)
```

Additional notes: need to install [httpuv](https://cran.r-project.org/web/packages/httpuv/index.html) package

**Comment by teramonagi** [comment]
@squirrelB @af12066 

Thank you for informing me this bug and I'm sorry for my late reply.
After some research, I realized that this problem was caused by The change of API specification.
See the [this](https://community.fitbit.com/t5/Web-API-Development/Invalid-authorization-header-format/td-p/1363901) and [this](https://community.fitbit.com/t5/Web-API-Development/Trouble-with-OAuth-2-0-Tutorial/m-p/1617571#M6583) links in details.

I fixed this problem in this PR https://github.com/teramonagi/fitbitr/pull/25.

Thanks!
