### ISSUE TITLE
consumer key

### ISSUE THREAD

**Issue by ghost** [teramonagi/fitbitr#27]
Where do you find the consumer key for the fitbit API code?

**Comment by teramonagi** [comment]
Create your own account and log inhere
- https://dev.fitbit.com/login

Choose [Tools] -> [Register A Web App]
![image](https://user-images.githubusercontent.com/683736/32300838-ace7d47c-bf9e-11e7-81ca-66137236afb8.png)

After registration, you can find the information in [MANAGE MY APPS]
![image](https://user-images.githubusercontent.com/683736/32300916-09739ce4-bf9f-11e7-9c18-ff4682bee2c4.png)

I will write this information at README.md
Is that enough information for you?
