### ISSUE TITLE
Error in token

### ISSUE THREAD

**Issue by ghost** [teramonagi/fitbitr#28]
When I tried to create a token using "token <- oauth_token()" there was this error
"Error in base64encode(charToRaw(paste0(key, ":", secret))) : 
  could not find function "base64encode"

**Comment by jlweichen** [comment]
It seems this issue is worked around by making sure you load library(caTools). That library should be loaded as a dependency though.

**Comment by teramonagi** [comment]
I already checked my code and found that "there is no code using `base64encode`" .
It might be a problem of the other package.
From the error message you pasted here, I think that you should install  [base64decode](https://www.rdocumentation.org/packages/caTools/versions/1.17.1/topics/base64encode%20%26%20base64decode) package.
