### ISSUE TITLE
get_activity_intraday_time_series error when specifying start and end times

### ISSUE THREAD

**Issue by mahorst** [teramonagi/fitbitr#31]
The get_activity_intraday_time_series gives an error when specifying start and end times. The error back from Fitbit is "Time range should not be bigger than 24 hours." In the function "get_activity_intraday_time_series", line 91 should be: date2 <- "1d". See https://dev.fitbit.com/reference/web-api/activity/

After this correction, the get_activity_intraday_time_series function works correctly when specifying start and end times.

**Comment by teramonagi** [comment]
Could you show the entire sample code because everything looks fine on my machine?

```r
> fitbitr::get_activity_intraday_time_series(token, "steps", date="2017-12-15")
                  time value
1  2017-12-15 00:00:00     0
2  2017-12-15 00:15:00     0
3  2017-12-15 00:30:00     0
...
94 2017-12-15 23:15:00    32
95 2017-12-15 23:30:00   557
96 2017-12-15 23:45:00   318
```

**Comment by teramonagi** [comment]
Oops, I realized my mistake.
Fix it quickly.

```r
> fitbitr::get_activity_intraday_time_series(token, "steps", date="2017-12-15", start_time="05:45", end_time="22:30")
 Show Traceback
 
 Rerun with Debug
 Error in check_response(httr::GET(url = url, httr::config(token = token))) : 
  http_400 in paste0(httr::http_condition(response, "message"), httr::content(response, : Bad Request (HTTP 400).
{"errors":[{"errorType":"request","fieldName":"n/a","message":"Time range should not be bigger then 24 hours."}]} 
```

**Comment by teramonagi** [comment]
@mahorst 
I fixed this bug in https://github.com/teramonagi/fitbitr/pull/32 .
You can use this package without this problem if you can reinstall the latest version of this package.

Thank you for reporting this bug!

**Comment by mahorst** [comment]
Thanks for the quick turnaround.
