### ISSUE TITLE
Values Different From Those Downloaded from Fitbit

### ISSUE THREAD

**Issue by ghost** [teramonagi/fitbitr#34]
Hello,
Values for the following differ from those that are downloaded from Fitbit:
Distance
Number of Awakenings
Weight

Also, is there a way to pull minutes light sleep, deep sleep, and rem?
Thanks!

**Comment by teramonagi** [comment]
I'm trying to do a refactoring for this package.
Please wait a little longer.

**Comment by teramonagi** [comment]
It might be related to this (memo for myself).
https://dev.fitbit.com/reference/web-api/basics/#units

**Comment by ghost** [comment]
Thanks so much. This is a great package.

**Comment by teramonagi** [comment]
Hi @bwnuo .

Now, I'm fixing this problem and it is almost finished in [this PR](https://github.com/teramonagi/fitbitr/pull/35
).
But I'm not sure that this works in your case.
Could you try the following commands to install new dev-version?
```r
devtools::install_github("teramonagi/fitbitr@issues-34")
```

And after that, you can do like this
```r
# Token with different language (precisely speaking, it is not language but "unit" for measurement)
token <- fitbitr::oauth_token()
token <- fitbitr::oauth_token(language="en_US")
token <- fitbitr::oauth_token(language="en_GB")
# 
get_body_fat_logs(token, date="2018-01-04")
get_activity_time_series(token, "distance", date="2017-12-31", period="7d")
```
I already checked "distance" case, but I need to check more in body fat etc cases.

**Comment by ghost** [comment]
That totally worked! Is there a way to pull lean mass weight and fat mass weight? Thanks so much!


________________________________________
Benjamin Nelson, M.S.

**Comment by teramonagi** [comment]
Hi bwnuo

I would like to do refactoring including these functionalities.
Wait for a new release!

**Comment by teramonagi** [comment]
Fixed in [this PR](https://github.com/teramonagi/fitbitr/pull/35)
