### ISSUE TITLE
object 'convert_content_to_r_object' not found

### ISSUE THREAD

**Issue by cosmomeese** [teramonagi/fitbitr#38]
Minimum working (failing) example:
library(httr)
library(base64enc)
library(fitbitr)
KEY<- # INSERT YOURS HERE #
SECRET <- # INSERT YOURS HERE #
CALLBACK <- "http://localhost:1410/"
token <- fitbitr::oauth_token(key=KEY, secret=SECRET, callback=CALLBACK )
fitbitr::get_devices(token)

Results in the following error: object 'convert_content_to_r_object' not found. 
It seems like your package is the only place on the internet with a function name like that (google returns only 3 hits) and looking through your source code I can't actually find that function defined.

**Comment by teramonagi** [comment]
Hi @cosmomeese .
I fixed this problem in PR https://github.com/teramonagi/fitbitr/pull/40 .

You can update this package using
```
devtools::install_github("teramonagi/fitbitr")
```

**Comment by cosmomeese** [comment]
Awesome. Thanks! :)
